const express=require('express');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const app=express();
app.use(express.json({limit:'2mb'}));
app.use(express.static(__dirname));

const DB_FILE=path.join(__dirname,'data','db.json');
fs.mkdirSync(path.dirname(DB_FILE),{recursive:true});
function freshDB(){return {adminPassword:'ADMIN',members:[],pins:[],messages:[],levelTrack:{requests:[],upgrades:[],incomingPayments:[]}}}
function load(){try{return JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}catch(e){const d=freshDB();save(d);return d}}
function save(d){fs.writeFileSync(DB_FILE,JSON.stringify(d,null,2))}
let db=load();
if(!db.messages)db.messages=[];
if(!db.levelTrack)db.levelTrack={requests:[],upgrades:[],incomingPayments:[]};
if(!db.levelTrack.requests)db.levelTrack.requests=[];
if(!db.levelTrack.upgrades)db.levelTrack.upgrades=[];
if(!db.levelTrack.incomingPayments)db.levelTrack.incomingPayments=[];
for(const m of db.members){if(!m.level)m.level=1;if(!m.joinedAt)m.joinedAt=m.registeredAt||new Date().toISOString();}
save(db);

function id(){return 'B5-'+crypto.randomBytes(3).toString('hex').toUpperCase()}
function pin(){return 'B5-'+crypto.randomBytes(3).toString('hex').toUpperCase()}
function levelMemberId(level){const used=db.members.map(m=>String(m.levelMemberId||''));let n=1;while(used.includes(`L${level}-${String(n).padStart(3,'0')}`))n++;return `L${level}-${String(n).padStart(3,'0')}`}
function memberPublic(m){return {memberId:m.memberId,name:m.name,mobile:m.mobile,status:m.status,referral:m.referral,level:m.level||1,levelMemberId:m.levelMemberId||null,joinedAt:m.joinedAt||m.registeredAt||null,upgradeDate:m.upgradeDate||null}}
function findMember(q){q=String(q||'').toLowerCase();return db.members.filter(m=>(m.name+' '+m.memberId+' '+(m.levelMemberId||'')+' '+m.mobile).toLowerCase().includes(q))}
function descendants(rootId){
 let levels={1:[],2:[],3:[],4:[],5:[],6:[],7:[]},current=[rootId];
 for(let l=1;l<=7;l++){const next=db.members.filter(m=>current.includes(m.referral)).map(m=>m.memberId);levels[l]=db.members.filter(m=>next.includes(m.memberId));current=next;if(!current.length)break}
 return levels;
}
function tree(rootId){
 const root=db.members.find(m=>m.memberId===rootId);if(!root)return {name:'நீங்கள்',id:'Not Registered',children:[]};
 const kids=(id)=>db.members.filter(m=>m.referral===id).map(m=>({name:m.name,id:m.memberId,levelMemberId:m.levelMemberId||null,mobile:m.mobile,level:m.level||1,status:m.status,children:kids(m.memberId)}));
 return {name:root.name,id:root.memberId,levelMemberId:root.levelMemberId||null,mobile:root.mobile,level:root.level||1,status:root.status,children:kids(root.memberId)};
}
function wallet(memberId){const ps=db.pins.filter(p=>p.assignedTo===memberId);return {received:ps.length,used:ps.filter(p=>p.status==='USED').length,available:ps.filter(p=>p.status==='AVAILABLE').length,pins:ps.slice(-50)}}
function getMember(id){return db.members.find(m=>m.memberId===id)}
function levelAmount(from){return ({1:1000,2:3000,3:20000,4:100000,5:200000,6:500000}[from]||0)}
function upgradeForMember(id){const m=getMember(id);return m?db.levelTrack.upgrades.find(u=>u.memberId===id&&u.from===m.level&&!u.adminApproved):null}

app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'member.html')));
app.get('/member.html',(req,res)=>res.sendFile(path.join(__dirname,'member.html')));
app.get('/admin.html',(req,res)=>res.sendFile(path.join(__dirname,'admin.html')));

// BORNTOWIN5 server routes
app.post('/api/admin/login',(req,res)=>{if(req.body.password!==db.adminPassword)return res.status(401).json({error:'Incorrect password'});res.json({ok:true})});
app.post('/api/admin/password',(req,res)=>{if(req.body.oldPassword!==db.adminPassword)return res.status(401).json({error:'Current password is incorrect'});db.adminPassword=String(req.body.newPassword||'');save(db);res.json({ok:true})});
app.get('/api/admin/dashboard',(req,res)=>{const total=db.members.length,pending=db.members.filter(m=>m.status==='Pending').length,verified=db.members.filter(m=>m.status==='Verified').length;const report=db.members.map(m=>{const w=wallet(m.memberId);return {name:m.name,memberId:m.memberId,received:w.received,used:w.used,available:w.available}});res.json({total,pending,verified,todayRegistrations:db.members.filter(m=>(m.registeredAt||'').slice(0,10)===new Date().toISOString().slice(0,10)).length,pinSummary:{sent:db.pins.length,used:db.pins.filter(p=>p.status==='USED').length,leaders:db.members.filter(m=>db.pins.some(p=>p.assignedTo===m.memberId)).length},members:db.members.map(memberPublic),pinReport:report})});
app.get('/api/admin/members',(req,res)=>res.json({members:findMember(req.query.q).map(memberPublic)}));
app.get('/api/admin/member-details/:id',(req,res)=>{const m=getMember(req.params.id);if(!m)return res.status(404).json({error:'Member not found'});res.json({member:{...m,pin:undefined}})});
app.post('/api/admin/member-status',(req,res)=>{const m=getMember(req.body.memberId);if(!m)return res.status(404).json({error:'Member not found'});m.status=req.body.status;if(m.status==='Verified'&&!m.levelMemberId)m.levelMemberId=levelMemberId(m.level||1);save(db);res.json({ok:true,member:memberPublic(m)})});
app.post('/api/admin/message',(req,res)=>{if(req.body.to==='all'){db.messages.push({to:'ALL',message:req.body.message,at:new Date().toISOString()})}else{if(!getMember(req.body.memberId))return res.status(404).json({error:'Member not found'});db.messages.push({to:req.body.memberId,message:req.body.message,at:new Date().toISOString()})}save(db);res.json({ok:true})});
app.post('/api/admin/pins/generate',(req,res)=>{const m=getMember(req.body.memberId);if(!m)return res.status(404).json({error:'Member not found'});const n=Math.min(500,Math.max(1,Number(req.body.quantity)||1)),out=[];for(let i=0;i<n;i++){let p=pin();while(db.pins.some(x=>x.pin===p))p=pin();const row={pin:p,assignedTo:m.memberId,status:'AVAILABLE',usedBy:null,createdAt:new Date().toISOString()};db.pins.push(row);out.push(row)}save(db);const w=wallet(m.memberId);res.json({pins:out,member:memberPublic(m),available:w.available,used:w.used})});
app.get('/api/member/messages/:id',(req,res)=>{const id=req.params.id;if(!getMember(id))return res.status(404).json({error:'Member not found'});res.json({messages:db.messages.filter(x=>x.to==='ALL'||x.to===id).sort((a,b)=>String(b.at).localeCompare(String(a.at)))})});
app.post('/api/member/send-otp',(req,res)=>{if(!/^\d{10}$/.test(String(req.body.mobile||'')))return res.status(400).json({error:'Invalid mobile number'});res.json({ok:true,otp:'123456'})});
app.post('/api/member/login',(req,res)=>{const m=db.members.find(x=>x.mobile===req.body.mobile);if(req.body.otp!=='123456')return res.status(401).json({error:'OTP சரியாக இல்லை'});if(!m)return res.status(404).json({error:'Member not found. Please register first.'});res.json({member:memberPublic(m)})});
app.post('/api/member/check-pin',(req,res)=>{const p=String(req.body.pin||'').toUpperCase();if(!db.pins.some(x=>x.pin===p&&x.status==='AVAILABLE'))return res.status(400).json({error:'Invalid or unavailable Joining PIN'});res.json({ok:true})});
app.post('/api/member/register',(req,res)=>{const b=req.body;if(db.members.some(m=>m.mobile===b.mobile))return res.status(409).json({error:'Mobile number already registered'});const p=String(b.pin||'').toUpperCase(),pr=db.pins.find(x=>x.pin===p&&x.status==='AVAILABLE');if(!pr)return res.status(400).json({error:'Invalid or unavailable Joining PIN'});if(b.referral!=='FIRST MEMBER'&&!getMember(b.referral))return res.status(400).json({error:'Invalid Referral ID'});const m={...b,memberId:id(),status:'Pending',level:1,levelMemberId:null,registeredAt:new Date().toISOString(),joinedAt:new Date().toISOString()};delete m.pin;db.members.push(m);pr.status='USED';pr.usedBy=m.memberId;pr.usedAt=new Date().toISOString();save(db);res.json({member:memberPublic(m)})});
app.get('/api/member/dashboard/:id',(req,res)=>{const m=getMember(req.params.id);if(!m)return res.status(404).json({error:'Member not found'});const lv=descendants(m.memberId),w=wallet(m.memberId),levels={};for(let i=1;i<=7;i++)levels[i]=lv[i].map(memberPublic);res.json({member:memberPublic(m),levels,tree:tree(m.memberId),wallet:w})});
app.get('/api/member/level/:id/:level',(req,res)=>{const m=getMember(req.params.id),l=Number(req.params.level);if(!m||l<1||l>7)return res.status(404).json({error:'Not found'});const lv=descendants(m.memberId);res.json({members:lv[l].map(memberPublic)})});
app.post('/api/member/use-pin',(req,res)=>{const p=db.pins.find(x=>x.assignedTo===req.body.memberId&&x.status==='AVAILABLE');if(!p)return res.status(400).json({error:'No available PIN'});p.status='USED';p.usedBy=req.body.memberId;p.usedAt=new Date().toISOString();save(db);res.json({wallet:wallet(req.body.memberId)})});

// LEVELTRACK: all state is persisted in the same server database.
app.get('/api/leveltrack/admin/dashboard',(req,res)=>{const levels={};for(let i=1;i<=7;i++)levels[i]=db.members.filter(m=>(m.level||1)===i).length;res.json({levels,members:db.members.map(memberPublic),requests:db.levelTrack.requests,upgrades:db.levelTrack.upgrades,incomingPayments:db.levelTrack.incomingPayments})});
app.get('/api/leveltrack/admin/members',(req,res)=>res.json({members:findMember(req.query.q).map(memberPublic)}));
app.get('/api/leveltrack/admin/member-details/:id',(req,res)=>{const m=getMember(req.params.id);if(!m)return res.status(404).json({error:'Member not found'});const kids=db.members.filter(x=>x.referral===m.memberId);res.json({member:memberPublic(m),directReferrals:kids.length,totalDownline:(function count(id){return db.members.filter(x=>x.referral===id).reduce((n,x)=>n+1+count(x.memberId),0)})(m.memberId),tree:tree(m.memberId)})});
app.get('/api/leveltrack/admin/requests',(req,res)=>res.json({requests:db.levelTrack.requests.map(r=>({...r,member:memberPublic(getMember(r.memberId)||{})}))}));
app.post('/api/leveltrack/admin/requests/:id/assign',(req,res)=>{const r=db.levelTrack.requests.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({error:'Upgrade request not found'});const m=getMember(r.memberId);if(!m)return res.status(404).json({error:'Member not found'});if(m.level>=7)return res.status(400).json({error:'Level 7 is final'});const b=req.body||{};if(!b.payee||!b.payeeId||!b.account||!b.bank||!b.ifsc||!b.upi||!Number(b.amount))return res.status(400).json({error:'Receiver name, member ID, amount, account, bank, IFSC and UPI are required'});let u=upgradeForMember(m.memberId);if(!u){u={id:'UP-'+crypto.randomBytes(4).toString('hex').toUpperCase(),requestId:r.id,memberId:m.memberId,from:m.level,to:m.level+1,amount:0,payee:'',payeeId:'',account:'',bank:'',ifsc:'',upi:'',detailsSent:false,memberPaid:false,utr:'',receiverApproved:false,adminApproved:false,date:'',createdAt:new Date().toISOString()};db.levelTrack.upgrades.push(u)}u.requestId=r.id;Object.assign(u,{amount:Number(b.amount),payee:String(b.payee),payeeId:String(b.payeeId),account:String(b.account),bank:String(b.bank),ifsc:String(b.ifsc),upi:String(b.upi),detailsSent:true});r.status='Approved - Details Sent';r.updatedAt=new Date().toISOString();save(db);res.json({ok:true,request:r,upgrade:u})});
app.get('/api/leveltrack/admin/payments',(req,res)=>res.json({payments:db.levelTrack.incomingPayments}));
app.post('/api/leveltrack/admin/payments/:id/verify',(req,res)=>{const p=db.levelTrack.incomingPayments.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Payment not found'});if(!p.memberAccepted)return res.status(400).json({error:'Receiver/member must accept first'});p.adminApproved=true;p.status='Verified';p.verifiedAt=new Date().toISOString();save(db);res.json({ok:true,payment:p})});
app.get('/api/leveltrack/admin/upgrades',(req,res)=>res.json({upgrades:db.levelTrack.upgrades}));
app.post('/api/leveltrack/admin/upgrades/:id/final-approve',(req,res)=>{const u=db.levelTrack.upgrades.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({error:'Upgrade not found'});const m=getMember(u.memberId);if(!m)return res.status(404).json({error:'Member not found'});if(!u.memberPaid||!u.receiverApproved)return res.status(400).json({error:'Member payment + receiver approval required'});if(!db.levelTrack.incomingPayments.some(p=>p.upgradeId===u.id&&p.memberAccepted&&p.adminApproved))return res.status(400).json({error:'Incoming payment must be receiver accepted and admin verified'});u.adminApproved=true;u.date=new Date().toISOString().slice(0,10);m.level=u.to;m.levelMemberId=levelMemberId(u.to);m.upgradeDate=u.date;const r=db.levelTrack.requests.find(x=>x.id===u.requestId|| (x.memberId===m.memberId&&x.from===u.from&&x.to===u.to));if(r)r.status='Completed';save(db);res.json({ok:true,member:memberPublic(m),upgrade:u})});
app.get('/api/leveltrack/admin/daily-report',(req,res)=>{const d=String(req.query.date||new Date().toISOString().slice(0,10));const arr=db.levelTrack.upgrades.filter(u=>u.adminApproved&&u.date===d).map(u=>({...u,member:memberPublic(getMember(u.memberId)||{})}));res.json({date:d,count:arr.length,upgrades:arr})});

app.get('/api/leveltrack/member/dashboard/:id',(req,res)=>{const m=getMember(req.params.id);if(!m)return res.status(404).json({error:'Member not found'});const kids=db.members.filter(x=>x.referral===m.memberId);const down=(id)=>db.members.filter(x=>x.referral===id).reduce((n,x)=>n+1+down(x.memberId),0);const u=upgradeForMember(m.memberId);const reqs=db.levelTrack.requests.filter(r=>r.memberId===m.memberId);const incoming=db.levelTrack.incomingPayments.filter(p=>p.receiverMemberId===m.memberId);res.json({member:memberPublic(m),directReferrals:kids.length,totalDownline:down(m.memberId),tree:tree(m.memberId),upgrade:u,requests:reqs,incomingPayments:incoming,history:db.levelTrack.upgrades.filter(x=>x.memberId===m.memberId).sort((a,b)=>String(b.date).localeCompare(String(a.date)))})});
app.post('/api/leveltrack/member/upgrade-request',(req,res)=>{const m=getMember(req.body.memberId);if(!m)return res.status(404).json({error:'Member not found'});if(m.level>=7)return res.status(400).json({error:'Level 7 is final'});if(m.status!=='Verified')return res.status(400).json({error:'Membership must be verified before upgrade'});const active=upgradeForMember(m.memberId);if(active)return res.json({ok:true,upgrade:active,existing:true});const existing=db.levelTrack.requests.find(r=>r.memberId===m.memberId&&r.from===m.level&&r.to===m.level+1&&r.status!=='Completed');if(existing)return res.json({ok:true,request:existing,existing:true});const r={id:'REQ-'+crypto.randomBytes(4).toString('hex').toUpperCase(),memberId:m.memberId,from:m.level,to:m.level+1,amount:levelAmount(m.level),date:new Date().toISOString().slice(0,10),status:'Requested',createdAt:new Date().toISOString()};db.levelTrack.requests.push(r);save(db);res.json({ok:true,request:r})});
app.post('/api/leveltrack/member/upgrade/:id/pay',(req,res)=>{const u=db.levelTrack.upgrades.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({error:'Upgrade not found'});if(u.memberId!==req.body.memberId)return res.status(403).json({error:'Not your upgrade'});const utr=String(req.body.utr||'').trim();if(!utr)return res.status(400).json({error:'UTR / Transaction Number required'});u.memberPaid=true;u.utr=utr;u.paidAt=new Date().toISOString();let p=db.levelTrack.incomingPayments.find(x=>x.upgradeId===u.id);if(!p){p={id:'PAY-'+crypto.randomBytes(4).toString('hex').toUpperCase(),upgradeId:u.id,receiverMemberId:getMember(u.payeeId)?u.payeeId:null,memberId:u.memberId,fromMemberId:u.memberId,from:getMember(u.memberId)?.name||'',toMemberId:u.payeeId,to:u.payee,amount:u.amount,utr,memberAccepted:false,adminApproved:false,status:'Pending Receiver Acceptance',date:new Date().toISOString().slice(0,10)};db.levelTrack.incomingPayments.push(p)}else{p.utr=utr;p.status='Pending Receiver Acceptance'}save(db);res.json({ok:true,upgrade:u,payment:p})});
app.post('/api/leveltrack/member/incoming/:id/accept',(req,res)=>{const p=db.levelTrack.incomingPayments.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Payment not found'});if(p.receiverMemberId!==req.body.memberId)return res.status(403).json({error:'Not the receiver'});p.memberAccepted=true;p.status='Pending Admin Verification';p.acceptedAt=new Date().toISOString();const u=db.levelTrack.upgrades.find(x=>x.id===p.upgradeId);if(u)u.receiverApproved=true;save(db);res.json({ok:true,payment:p})});
app.get('/api/leveltrack/member/messages/:id',(req,res)=>{const id=req.params.id;if(!getMember(id))return res.status(404).json({error:'Member not found'});res.json({messages:db.messages.filter(x=>x.to==='ALL'||x.to===id)})});

const PORT=process.env.PORT||10000;
app.listen(PORT,'0.0.0.0',()=>console.log('BORNTOWIN5 + LEVELTRACK running on '+PORT));
