const express=require('express');
const fs=require('fs'); const path=require('path');
const app=express(); app.use(express.json({limit:'5mb'}));
const PORT=process.env.PORT||3000;
const DATA=process.env.DATA_FILE||path.join(__dirname,'data','db.json');
function load(){try{return JSON.parse(fs.readFileSync(DATA,'utf8'))}catch(e){return {members:[],pins:[{pin:'B5-557269',status:'AVAILABLE',assignedTo:null,usedBy:null}],messages:[],pending:[]}}}
let db=load(); function save(){fs.mkdirSync(path.dirname(DATA),{recursive:true});fs.writeFileSync(DATA,JSON.stringify(db,null,2))}
function rid(){let x; do{x='B5-'+Math.floor(100000+Math.random()*900000)}while(db.members.some(m=>m.id===x)||db.pins.some(p=>p.pin===x)); return x}
function pin(){let x; do{x='B5-'+Math.floor(100000+Math.random()*900000)}while(db.pins.some(p=>p.pin===x)||db.members.some(m=>m.id===x)); return x}
function levels(member){let out=[];let parents=new Set([member.id]);for(let l=1;l<=7;l++){let ids=db.members.filter(m=>parents.has(m.referralId)).map(m=>m.id);out.push(db.members.filter(m=>ids.includes(m.id)).map(m=>({id:m.id,name:m.name,mobile:m.mobile,status:m.status})));parents=new Set(ids);if(!ids.length)break}return out}
app.get('/',(req,res)=>res.redirect('/member.html'));
app.get('/member.html',(req,res)=>res.sendFile(path.join(__dirname,'member.html')));
app.get('/admin.html',(req,res)=>res.sendFile(path.join(__dirname,'admin.html')));
app.get('/api/health',(req,res)=>res.json({ok:true,app:'BORNTOWIN5',dynamic:true}));
app.post('/api/admin/login',(req,res)=>{if(req.body.password==='ADMIN')return res.json({ok:true});res.status(401).json({error:'Invalid admin password'})});
app.post('/api/otp/request',(req,res)=>{const mobile=String(req.body.mobile||'').trim();const m=db.members.find(x=>x.mobile===mobile);if(!/^\d{10}$/.test(mobile)||!m)return res.status(404).json({error:'இந்த Mobile Number பதிவு செய்யப்படவில்லை.'});res.json({ok:true,testingOtp:'123456',memberId:m.id})});
app.post('/api/member/login',(req,res)=>{const mobile=String(req.body.mobile||'').trim();if(req.body.otp!=='123456')return res.status(401).json({error:'Invalid OTP'});const m=db.members.find(x=>x.mobile===mobile);if(!m)return res.status(404).json({error:'Member not found'});res.json({ok:true,member:{id:m.id,name:m.name,mobile:m.mobile,status:m.status,referralId:m.referralId}})});
app.get('/api/member/:id',(req,res)=>{const m=db.members.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({error:'Not found'});res.json({member:m,levels:levels(m),messages:db.messages.filter(x=>x.to==='ALL'||x.to===m.id)})});
app.post('/api/register',(req,res)=>{const b=req.body||{};const required=['pin','name','gender','age','edu','cat','skill','address','nominee','mobile','account','ifsc','bank','branch'];for(const k of required)if(!String(b[k]||'').trim())return res.status(400).json({error:'அனைத்து கட்டாய விவரங்களையும் நிரப்பவும்.'});if(!b.dec)return res.status(400).json({error:'Declaration-ஐ tick செய்யவும்.'});const ref=b.ref||'FIRST MEMBER';if(ref!=='FIRST MEMBER'&&!db.members.some(m=>m.id===ref))return res.status(400).json({error:'Referral ID valid இல்லை.'});if(db.members.some(m=>m.mobile===String(b.mobile).trim()))return res.status(400).json({error:'Mobile Number ஏற்கனவே உள்ளது.'});const p=db.pins.find(x=>x.pin===String(b.pin).trim()&&x.status==='AVAILABLE');if(!p)return res.status(400).json({error:'Joining PIN valid / available இல்லை.'});const id=rid();const m={id,name:String(b.name).trim(),gender:b.gender,age:b.age,education:b.edu,category:b.cat,skill:b.skill,address:b.address,nominee:b.nominee,mobile:String(b.mobile).trim(),account:b.account,ifsc:b.ifsc,bank:b.bank,branch:b.branch,referralId:ref,status:'ACTIVE',createdAt:new Date().toISOString()};db.members.push(m);p.status='USED';p.usedBy=id;p.assignedTo=p.assignedTo||null;save();res.json({ok:true,member:m,referralLink:'/member.html?ref='+id})});
app.get('/api/admin/members',(req,res)=>res.json({members:db.members,pending:db.pending}));
app.post('/api/admin/pins/generate',(req,res)=>{const count=Math.max(1,Math.min(500,Number(req.body.count)||1));const assignedTo=req.body.assignedTo||null;const created=[];for(let i=0;i<count;i++){const p={pin:pin(),status:'AVAILABLE',assignedTo,usedBy:null,createdAt:new Date().toISOString()};db.pins.push(p);created.push(p)}save();res.json({created,stats:{generated:db.pins.length,used:db.pins.filter(x=>x.status==='USED').length,available:db.pins.filter(x=>x.status==='AVAILABLE').length}})});
app.get('/api/admin/pins',(req,res)=>res.json({pins:db.pins,stats:{generated:db.pins.length,used:db.pins.filter(x=>x.status==='USED').length,available:db.pins.filter(x=>x.status==='AVAILABLE').length}}));
app.post('/api/admin/messages',(req,res)=>{const text=String(req.body.text||'').trim();const to=req.body.to||'ALL';if(!text)return res.status(400).json({error:'Message எழுதவும்.'});const msg={id:Date.now(),to,text,createdAt:new Date().toISOString()};db.messages.push(msg);save();res.json({ok:true,message:msg})});
app.post('/api/admin/review',(req,res)=>{const {memberId,action}=req.body;const m=db.members.find(x=>x.id===memberId);if(!m)return res.status(404).json({error:'Member not found'});if(!['VERIFY','REJECT'].includes(action))return res.status(400).json({error:'Invalid action'});m.status=action==='VERIFY'?'VERIFIED':'REJECTED';save();res.json({ok:true,member:m})});
app.get('/api/admin/tree',(req,res)=>res.json({members:db.members}));
app.listen(PORT,()=>console.log(`BORNTOWIN5 running on port ${PORT}`));
