const express=require('express');
const fs=require('fs'); const path=require('path'); const crypto=require('crypto');
const app=express(); app.use(express.json({limit:'5mb'})); app.use(express.static(__dirname));
const DATA=process.env.DATA_FILE||path.join(__dirname,'data','db.json');
fs.mkdirSync(path.dirname(DATA),{recursive:true});
const INITIAL_PIN='B5-FMUXNF';
function freshDB(){return {adminPassword:'ADMIN',members:[],pins:[],messages:[],leveltrack:{requests:[],upgrades:[],payments:[]}}}
function load(){try{return JSON.parse(fs.readFileSync(DATA,'utf8'))}catch(e){const d=freshDB();save(d);return d}}
function save(d=db){fs.writeFileSync(DATA,JSON.stringify(d,null,2))}
let db=load();
if(!Array.isArray(db.members))db.members=[]; if(!Array.isArray(db.pins))db.pins=[]; if(!Array.isArray(db.messages))db.messages=[];
if(!db.leveltrack)db.leveltrack={requests:[],upgrades:[],payments:[]};
for(const k of ['requests','upgrades','payments'])if(!Array.isArray(db.leveltrack[k]))db.leveltrack[k]=[];
// Preserve existing data; add the documented first PIN only when the database has no members and that PIN is absent.
if(db.members.length===0 && !db.pins.some(p=>p.pin===INITIAL_PIN))db.pins.push({pin:INITIAL_PIN,assignedTo:null,status:'AVAILABLE',usedBy:null,createdAt:new Date().toISOString(),initial:true});
save();
function rid(prefix='LT'){return prefix+'-'+crypto.randomBytes(5).toString('hex').toUpperCase()}
function b5id(){return 'B5-'+crypto.randomBytes(3).toString('hex').toUpperCase()}
function pin(){return 'B5-'+crypto.randomBytes(3).toString('hex').toUpperCase()}
function publicMember(m){return {memberId:m.memberId,name:m.name,mobile:m.mobile,status:m.status,referral:m.referral,level:m.level||1,levelMemberId:m.levelMemberId||null,joinedAt:m.joinedAt||m.registeredAt||null,upgradeDate:m.upgradeDate||null}}
function findMember(q){q=String(q||'').toLowerCase();return db.members.filter(m=>(m.name+' '+m.memberId+' '+m.mobile).toLowerCase().includes(q))}
function descendants(rootId){let levels={1:[],2:[],3:[],4:[],5:[],6:[],7:[]},cur=[rootId];for(let l=1;l<=7;l++){const ids=db.members.filter(m=>cur.includes(m.referral)).map(m=>m.memberId);levels[l]=db.members.filter(m=>ids.includes(m.memberId));cur=ids;if(!cur.length)break}return levels}
function tree(rootId){const root=db.members.find(m=>m.memberId===rootId);if(!root)return {name:'நீங்கள்',id:'Not Registered',children:[]};const kids=id=>db.members.filter(m=>m.referral===id).map(m=>({name:m.name,id:m.memberId,mobile:m.mobile,status:m.status,level:m.level||1,levelMemberId:m.levelMemberId,children:kids(m.memberId)}));return {name:root.name,id:root.memberId,mobile:root.mobile,status:root.status,level:root.level||1,levelMemberId:root.levelMemberId,children:kids(root.memberId)}}
function wallet(memberId){const ps=db.pins.filter(p=>p.assignedTo===memberId);return {received:ps.length,used:ps.filter(p=>p.status==='USED').length,available:ps.filter(p=>p.status==='AVAILABLE').length,pins:ps.filter(p=>p.status==='AVAILABLE').slice(-100)}}
function totalDownline(id){return Object.values(descendants(id)).reduce((n,a)=>n+a.length,0)}
function direct(id){return db.members.filter(m=>m.referral===id).length}
function ensureLevel(m){if(!m.level)m.level=1;if(!m.levelMemberId){const n=db.members.filter(x=>(x.level||1)===m.level).length+1;m.levelMemberId=`L${m.level}-${String(n).padStart(3,'0')}`}if(!m.joinedAt)m.joinedAt=m.registeredAt||new Date().toISOString()}
function levelAmount(level){return ({1:1000,2:3000,3:20000,4:100000,5:200000,6:500000})[level]||0}
function nextLevel(level){return level<7?level+1:null}
function activeMember(m){return m.status==='Verified'||m.status==='Approved'||m.status==='Active'}
function msgList(id){return db.messages.filter(x=>x.to===id||x.to==='ALL').sort((a,b)=>String(b.at).localeCompare(String(a.at)))}
app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'member.html')));
app.get('/member.html',(req,res)=>res.sendFile(path.join(__dirname,'member.html')));
app.get('/admin.html',(req,res)=>res.sendFile(path.join(__dirname,'admin.html')));
app.get('/leveltrack-admin.html',(req,res)=>res.sendFile(path.join(__dirname,'leveltrack-admin.html')));
app.get('/leveltrack-member.html',(req,res)=>res.sendFile(path.join(__dirname,'leveltrack-member.html')));
app.get('/api/health',(req,res)=>res.json({ok:true,app:'BORNTOWIN5',dynamic:true,leveltrack:true}));
// BORNTOWIN5 Admin
app.post('/api/admin/login',(req,res)=>{if(String(req.body.password||'')!==String(db.adminPassword))return res.status(401).json({error:'Incorrect password'});res.json({ok:true})});
app.post('/api/admin/password',(req,res)=>{if(String(req.body.oldPassword||'')!==String(db.adminPassword))return res.status(401).json({error:'Current password is incorrect'});db.adminPassword=String(req.body.newPassword||'');save();res.json({ok:true})});
app.get('/api/admin/dashboard',(req,res)=>{const total=db.members.length,pending=db.members.filter(m=>m.status==='Pending').length,verified=db.members.filter(m=>m.status==='Verified').length;const key=new Date().toISOString().slice(0,10);const todayRegistrations=db.members.filter(m=>String(m.registeredAt||'').slice(0,10)===key).length;const report=db.members.map(m=>{const w=wallet(m.memberId);return {name:m.name,memberId:m.memberId,received:w.received,used:w.used,available:w.available}});res.json({total,pending,verified,todayRegistrations,members:db.members.map(publicMember),pinSummary:{sent:db.pins.filter(p=>p.assignedTo).length,used:db.pins.filter(p=>p.status==='USED').length,leaders:new Set(db.pins.filter(p=>p.assignedTo).map(p=>p.assignedTo)).size},pinReport:report})});
app.get('/api/admin/members',(req,res)=>res.json({members:findMember(req.query.q).map(publicMember)}));
app.get('/api/admin/member-details/:id',(req,res)=>{const m=db.members.find(x=>x.memberId===req.params.id);if(!m)return res.status(404).json({error:'Member not found'});res.json({member:m})});
app.post('/api/admin/member-status',(req,res)=>{const m=db.members.find(x=>x.memberId===req.body.memberId);if(!m)return res.status(404).json({error:'Member not found'});m.status=req.body.status;if(activeMember(m)){ensureLevel(m)}save();res.json({ok:true,member:publicMember(m)})});
app.post('/api/admin/message',(req,res)=>{if(req.body.to==='all'){db.messages.push({to:'ALL',message:String(req.body.message||''),at:new Date().toISOString()})}else{if(!db.members.some(m=>m.memberId===req.body.memberId))return res.status(404).json({error:'Member not found'});db.messages.push({to:req.body.memberId,message:String(req.body.message||''),at:new Date().toISOString()})}save();res.json({ok:true})});
app.post('/api/admin/pins/generate',(req,res)=>{const m=db.members.find(x=>x.memberId===req.body.memberId);if(!m)return res.status(404).json({error:'Member not found'});const n=Math.min(500,Math.max(1,Number(req.body.quantity)||1)),out=[];for(let i=0;i<n;i++){let p=pin();while(db.pins.some(x=>x.pin===p))p=pin();const row={pin:p,assignedTo:m.memberId,status:'AVAILABLE',usedBy:null,createdAt:new Date().toISOString()};db.pins.push(row);out.push(row)}save();const w=wallet(m.memberId);res.json({pins:out,member:publicMember(m),available:w.available,used:w.used})});
// Member
app.post('/api/member/send-otp',(req,res)=>{if(!/^\d{10}$/.test(String(req.body.mobile||'')))return res.status(400).json({error:'Invalid mobile number'});res.json({ok:true,otp:'123456'})});
app.post('/api/member/login',(req,res)=>{const m=db.members.find(x=>x.mobile===String(req.body.mobile||''));if(String(req.body.otp)!=='123456')return res.status(401).json({error:'OTP சரியாக இல்லை'});if(!m)return res.status(404).json({error:'Member not found. Please register first.'});res.json({member:publicMember(m)})});
app.post('/api/member/check-pin',(req,res)=>{const p=String(req.body.pin||'').toUpperCase();const ok=db.pins.some(x=>x.pin===p&&x.status==='AVAILABLE') || (db.members.length===0&&p===INITIAL_PIN);if(!ok)return res.status(400).json({error:'Invalid or unavailable Joining PIN'});res.json({ok:true})});
app.post('/api/member/register',(req,res)=>{const b=req.body||{};if(db.members.some(m=>m.mobile===b.mobile))return res.status(409).json({error:'Mobile number already registered'});const p=String(b.pin||'').toUpperCase();let pr=db.pins.find(x=>x.pin===p&&x.status==='AVAILABLE');if(!pr && db.members.length===0 && p===INITIAL_PIN){pr={pin:INITIAL_PIN,assignedTo:null,status:'AVAILABLE',createdAt:new Date().toISOString(),initial:true};db.pins.push(pr)}if(!pr)return res.status(400).json({error:'Invalid or unavailable Joining PIN'});if(b.referral!=='FIRST MEMBER'&&!db.members.some(m=>m.memberId===b.referral))return res.status(400).json({error:'Invalid Referral ID'});const m={...b,memberId:b5id(),status:'Pending',registeredAt:new Date().toISOString(),level:1,levelMemberId:null};delete m.pin;db.members.push(m);pr.status='USED';pr.usedBy=m.memberId;pr.usedAt=new Date().toISOString();save();res.json({member:publicMember(m)})});
app.get('/api/member/messages/:id',(req,res)=>{if(!db.members.some(m=>m.memberId===req.params.id))return res.status(404).json({error:'Member not found'});res.json({messages:msgList(req.params.id)})});
app.get('/api/member/wallet/:id',(req,res)=>{if(!db.members.some(m=>m.memberId===req.params.id))return res.status(404).json({error:'Member not found'});res.json({pins:wallet(req.params.id).pins})});
app.get('/api/member/dashboard/:id',(req,res)=>{const m=db.members.find(x=>x.memberId===req.params.id);if(!m)return res.status(404).json({error:'Member not found'});ensureLevel(m);const lv=descendants(m.memberId),levels={};for(let i=1;i<=7;i++)levels[i]=lv[i].map(publicMember);save();res.json({member:publicMember(m),levels,tree:tree(m.memberId),wallet:wallet(m.memberId)})});
app.get('/api/member/level/:id/:level',(req,res)=>{const m=db.members.find(x=>x.memberId===req.params.id),l=Number(req.params.level);if(!m||l<1||l>7)return res.status(404).json({error:'Not found'});res.json({members:descendants(m.memberId)[l].map(publicMember)})});
app.post('/api/member/use-pin',(req,res)=>{const p=db.pins.find(x=>x.assignedTo===req.body.memberId&&x.status==='AVAILABLE');if(!p)return res.status(400).json({error:'No available PIN'});p.status='USED';p.usedBy=req.body.memberId;p.usedAt=new Date().toISOString();save();res.json({wallet:wallet(req.body.memberId)})});
// LevelTrack Admin
app.get('/api/leveltrack/admin/dashboard',(req,res)=>{const members=db.members.map(m=>{ensureLevel(m);return publicMember(m)});const levels={1:0,2:0,3:0,4:0,5:0,6:0,7:0};db.members.forEach(m=>levels[m.level||1]++);res.json({members,levels,requests:db.leveltrack.requests,upgrades:db.leveltrack.upgrades,payments:db.leveltrack.payments})});
app.get('/api/leveltrack/admin/members',(req,res)=>res.json({members:findMember(req.query.q).map(m=>{ensureLevel(m);return publicMember(m)})}));
app.get('/api/leveltrack/admin/member-details/:id',(req,res)=>{const m=db.members.find(x=>x.memberId===req.params.id);if(!m)return res.status(404).json({error:'Member not found'});ensureLevel(m);res.json({member:publicMember(m),directReferrals:direct(m.memberId),totalDownline:totalDownline(m.memberId),tree:tree(m.memberId)})});
app.post('/api/leveltrack/admin/requests/:id/assign',(req,res)=>{const r=db.leveltrack.requests.find(x=>x.id===req.params.id);if(!r||r.status!=='Requested')return res.status(404).json({error:'Pending upgrade request not found'});const m=db.members.find(x=>x.memberId===r.memberId);if(!m)return res.status(404).json({error:'Member not found'});const body=req.body||{};if(!body.payee||!body.amount||!body.account||!body.bank||!body.ifsc||!body.upi)return res.status(400).json({error:'All payment details are required'});const u=db.leveltrack.upgrades.find(x=>x.requestId===r.id)||{id:rid('UPG'),requestId:r.id,memberId:m.memberId,from:r.from,to:r.to,createdAt:new Date().toISOString()};Object.assign(u,{payee:String(body.payee),payeeId:String(body.payeeId||''),amount:Number(body.amount),account:String(body.account),bank:String(body.bank),ifsc:String(body.ifsc),upi:String(body.upi),detailsSent:true,adminApproved:false,memberPaid:false,receiverApproved:false});if(!db.leveltrack.upgrades.some(x=>x.id===u.id))db.leveltrack.upgrades.push(u);r.status='Assigned';r.assignedAt=new Date().toISOString();save();res.json({ok:true,upgrade:u})});
app.get('/api/leveltrack/admin/daily-report',(req,res)=>{const date=String(req.query.date||new Date().toISOString().slice(0,10));const upgrades=db.leveltrack.upgrades.filter(u=>u.adminApproved&&String(u.completedAt||'').slice(0,10)===date).map(u=>({from:u.from,to:u.to,amount:u.amount,date:u.completedAt,member:publicMember(db.members.find(m=>m.memberId===u.memberId)||{})}));res.json({date,count:upgrades.length,upgrades})});
app.post('/api/leveltrack/admin/payments/:id/verify',(req,res)=>{const p=db.leveltrack.payments.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Payment not found'});if(!p.memberAccepted)return res.status(400).json({error:'Receiver has not accepted the payment yet'});p.adminApproved=true;p.verifiedAt=new Date().toISOString();const u=db.leveltrack.upgrades.find(x=>x.id===p.upgradeId);if(u)u.receiverApproved=true;save();res.json({ok:true})});
app.post('/api/leveltrack/admin/upgrades/:id/final-approve',(req,res)=>{const u=db.leveltrack.upgrades.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({error:'Upgrade not found'});if(!u.memberPaid||!u.receiverApproved)return res.status(400).json({error:'Payment and receiver acceptance are required'});const m=db.members.find(x=>x.memberId===u.memberId);if(!m)return res.status(404).json({error:'Member not found'});m.level=u.to;m.levelMemberId=`L${m.level}-${String(db.members.filter(x=>x.level===m.level).length+1).padStart(3,'0')}`;m.upgradeDate=new Date().toISOString();u.adminApproved=true;u.completedAt=m.upgradeDate;const r=db.leveltrack.requests.find(x=>x.id===u.requestId);if(r)r.status='Completed';save();res.json({ok:true,member:publicMember(m)})});
// LevelTrack Member
app.get('/api/leveltrack/member/dashboard/:id',(req,res)=>{const m=db.members.find(x=>x.memberId===req.params.id);if(!m)return res.status(404).json({error:'Member not found'});ensureLevel(m);const current=m.level||1;const requests=db.leveltrack.requests.filter(r=>r.memberId===m.memberId);const upgrade=db.leveltrack.upgrades.filter(u=>u.memberId===m.memberId).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0]||null;const incoming=db.leveltrack.payments.filter(p=>p.receiverMemberId===m.memberId).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));const history=db.leveltrack.upgrades.filter(u=>u.memberId===m.memberId).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));save();res.json({member:publicMember(m),directReferrals:direct(m.memberId),totalDownline:totalDownline(m.memberId),tree:tree(m.memberId),requests,upgrade,incomingPayments:incoming,history})});
app.post('/api/leveltrack/member/upgrade-request',(req,res)=>{const m=db.members.find(x=>x.memberId===req.body.memberId);if(!m)return res.status(404).json({error:'Member not found'});ensureLevel(m);if(!activeMember(m))return res.status(400).json({error:'Member is not active yet'});if((m.level||1)>=7)return res.status(400).json({error:'Level 7 is the final level'});const open=db.leveltrack.requests.find(r=>r.memberId===m.memberId&&r.status!=='Completed');if(open)return res.status(400).json({error:'Upgrade request already pending'});const from=m.level||1,to=nextLevel(from);const r={id:rid('REQ'),memberId:m.memberId,from,to,status:'Requested',date:new Date().toISOString()};db.leveltrack.requests.push(r);save();res.json({ok:true,request:r})});
app.post('/api/leveltrack/member/upgrade/:id/pay',(req,res)=>{const u=db.leveltrack.upgrades.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({error:'Upgrade payment assignment not found'});if(u.memberId!==req.body.memberId)return res.status(403).json({error:'Not your upgrade'});const utr=String(req.body.utr||'').trim();if(!utr)return res.status(400).json({error:'UTR is required'});u.memberPaid=true;u.utr=utr;u.paidAt=new Date().toISOString();const receiver=db.members.find(m=>m.memberId===u.payeeId);if(receiver){let p=db.leveltrack.payments.find(x=>x.upgradeId===u.id);if(!p){p={id:rid('PAY'),upgradeId:u.id,receiverMemberId:receiver.memberId,fromMemberId:u.memberId,from:db.members.find(m=>m.memberId===u.memberId)?.name||u.memberId,to:receiver.name,amount:u.amount,utr,memberAccepted:false,adminApproved:false,createdAt:new Date().toISOString()};db.leveltrack.payments.push(p)}else Object.assign(p,{utr,amount:u.amount})}else{return res.status(400).json({error:'Receiver member not found'})}save();res.json({ok:true,upgrade:u})});
app.post('/api/leveltrack/member/incoming/:id/accept',(req,res)=>{const p=db.leveltrack.payments.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Incoming payment not found'});if(p.receiverMemberId!==req.body.memberId)return res.status(403).json({error:'Not your incoming payment'});p.memberAccepted=true;p.acceptedAt=new Date().toISOString();const u=db.leveltrack.upgrades.find(x=>x.id===p.upgradeId);if(u)u.receiverApproved=true;save();res.json({ok:true,payment:p})});
app.get('/api/leveltrack/member/messages/:id',(req,res)=>{if(!db.members.some(m=>m.memberId===req.params.id))return res.status(404).json({error:'Member not found'});res.json({messages:msgList(req.params.id)})});
const PORT=process.env.PORT||10000; app.listen(PORT,'0.0.0.0',()=>console.log('BORNTOWIN5 + LevelTrack running on '+PORT));
